### ISSUE TITLE
flickering autocompletion

### ISSUE THREAD

**Issue by kainbacher** [DamnWidget/anaconda#244]
if i use anaconda i have a flickering autocompletion.
[Link to Video](https://dl.dropboxusercontent.com/u/2994880/sublime-anaconda-flickering.mov)

any ideas?

**Comment by skaughtx0r** [comment]
I just ran across this problem on Windows. I dug through the Anaconda code and was able to fix the problem by commenting out line 82 in listeners/completion.py

```active_view().run_command("hide_auto_complete")```

It seems like every time ```on_query_completions``` is called (which is very frequently according to debug output), the window is hidden.

**Comment by DamnWidget** [comment]
@skaughtx0r that line is there for a reason, anconda's completion is an asynchronous operation, when the autocompletion is called, anaconda fires it to the JsonServer and return control to ST3 that shows it's regular + other plugins completions. When a response with a completion list comes from the async socket a callback is fired (that calls _complete) and then anaconda hides the already shown autocompletion box before to populate it with the new data, then fires the ST3 native auto completion to show the box again.

If ST3 is doing somethign weird on auto completion is probably because you have another plugin messing around with it (probably SublimeCodeIntel?).

**Comment by ankush981** [comment]
I had the same issue with Anaconda on ST3 and Ubuntu 14.04. Disabling Anacoda solved it, but that doesn't prove it was caused by Anaconda.

**Comment by DamnWidget** [comment]
Probably you had SublimeJedi active at the same time

**Comment by ankush981** [comment]
OMG that was it! :dancer: :dancer: Thank you so much! My ST3 experience has just improved by 300%! :smile:

**Comment by DamnWidget** [comment]
No problem

**Comment by Endogen** [comment]
If i have Anaconda running and also SublimeCodeIntel, i have the issue that i don't see any word completion while in a file that is not a python script. Any idea how to fix this? I would prefer to use Anacondas word completion in py files and use SublimeCodeIntel on everything else - is that possible? Should i open a new issue for that?

**Comment by DamnWidget** [comment]
Hi @Endogen 
Anaconda disables some plugins that are known to interfere badly with it when thy are present in the system, so, if anaconda is enabled it disables SublimeCodeIntel (between others), then if anaconda is unloaded or disabled, it enables again all those plugins.

This measure can look harsh but has been taken after many years of solving problems caused by 3rd party plugins that doesn't take into account how they can interfere or make other plugins totally misbehave. The only real solution to the problem would be if Sublime Text had a sandboxed environment where to run each plugin but sadly that doesn't happens (and it not gonna happen).

You have a couple of options here
1) Recommended: Just open the `Command Palette` and disable anaconda when you need to work with SublimeCodeIntel
2) Less Recommended: Disable the auto plugins disabling in anaconda https://github.com/DamnWidget/anaconda/blob/master/Anaconda.sublime-settings#L667-L671

I don't recommend you to disable the auto plugins disabling on anaconda as you will start to experiment really weird behavior due SublimeCodeIntel modifying how ST3 behave when a Python file is being edited (like showing autocompletion when you write a colon, what is totally stupid).

I hope this solved your doubts.

**Comment by Endogen** [comment]
Thanks for the explanation! I disabled Anaconda while working in non Python files.
