### ISSUE TITLE
ST3 freezes if vagrant_environment is set, but server is not running

### ISSUE THREAD

**Issue by MichalPodeszwa** [DamnWidget/anaconda#246]
This happens whether I've got the vagrant up and running or not. It's just important that I don't have the anaconda server on.

If I start the server, the autocomplete works like a charm.

I think the best would be to have a subprocess which sees if the server is running. If not, it uses default autocomplete, just as if the server was not running, And if it starts to respond it would use the server.

I'm using ST3 Build 3065. On Arch 64-bit.

**Comment by wldcordeiro** [comment]
This seems to still be present, I've tried to switch to my project that I configured and I end up having to kill the ST3 process. 

In my User settings I have
```
 "auto_project_switch": true,
```

and my project settings

```
		"vagrant_environment":
		{
			"directory": "~/Documents/Code/zion-env",
			"network":
			{
				"mode": "forwarded",
				"port": 19360
			}
		}
```

**Comment by DamnWidget** [comment]
Hi.
Anaconda is not able to switch from a regular interpreter to a vagrant one, this is already warned in the documentation as a note into the section [Configure Sublime Text 3 project](http://damnwidget.github.io/anaconda/vagrant/#toc_5). 

ST3 need to be restarted in order to make it just work due some limitations in the ST3 plugin architecture itself.

**Comment by wldcordeiro** [comment]
@DamnWidget Even when I restart it just freezes.

**Comment by rschamp** [comment]
> This happens whether I've got the vagrant up and running or not. It's just important that I don't have the anaconda server on.

I don't understand how the server process can be running without vagrant running. Isn't the point that the server runs on the vagrant machine?

I see the same thing has @wldcordeiro — if vagrant stops, then ST3 locks up.  This happens frequently on OS X when battery power is low, because apparently OS X reaps the vagrant process to conserve power.  If you vagrant resume, then ST3 becomes responsive again.

**Comment by tamakisquare** [comment]
I am experiencing the same issue as @wldcordeiro and @rschamp. The design of Anaconda's support for Vagrant assumes that the Vagrant guest environment is always on but that's generally not true. Vagrant is mainly used for development environment and because of that frequent restarts and shutdowns are not uncommon.

Restarting ST3 when the Vagrant guest environment is back on is the only way to get around the issue. But like @wldcordeiro mentioned, this approach does not work all the time for some unknown reason.

@DamnWidget , is it possible to implement disabling interpreter all together when the server process cannot be found? With this design, at least ST3 can still be used as a regular text editor, which is much better than a frozen editor that does only hindering productivity.

**Comment by wldcordeiro** [comment]
@tamakisquare I agree with what you propose. I think having a fallback to the default interpreter would save a lot of headache.

**Comment by DamnWidget** [comment]
There are several problems with the vagrant support on anaconda, first is that it has no maintainer.

There are already fallback mechanisms in place as you can see [https://github.com/DamnWidget/anaconda/blob/master/anaconda_lib/worker.py#L243-L245](here)

In Vagrant we have [https://github.com/DamnWidget/anaconda/blob/master/anaconda_lib/worker.py#L373-L396](this method) that checks if the vagrant is up but it does only on initialization then it's not checked ever again. Probably calling that method will be enough to add some fallback mechanism that uses a regular interpreter always warning the user about the situation.

Sadly I can dedicate a few to no time per week to the project myself, but PRs are welcome guys. If you think you can hook into the plugin and add the needed mechanics, please take a look at the [http://damnwidget.gitbooks.io/anacondast3-developers-documentation/](Anaconda's developers book) and get your hand dirty :)

**Comment by tamakisquare** [comment]
@DamnWidget , thanks for all the information on this issue and, of course, this wonderful Sublime Text plugin.

I would like to help but my time is also tied up at the moment :(

**Comment by tamakisquare** [comment]
@DamnWidget, would it be better to re-open this issue, so that it could have greater exposure for PRs? Just my two cents ;)
