### ISSUE TITLE
Adding a python_interpreter setting to .sublime-project file that uses the $project_path keeps giving false reports

### ISSUE THREAD

**Issue by jilves** [DamnWidget/anaconda#270]
![untitled](https://cloud.githubusercontent.com/assets/4486848/6096929/688b59b6-afb1-11e4-8770-4d7740493036.png)

This is on Windows 8.1 64-bit, trying to use a virtual environment created via pyvenv command.

When i set the "python_interpreter" variable value as a full path to the pyvenv's python.exe, everything works as expected.

When i use the build variable $project_path, the correct interpreter is also used (verified by checking sys.prefix) but i keep getting continuous popups:

![untitled](https://cloud.githubusercontent.com/assets/4486848/6096952/59ec8640-afb2-11e4-8e38-a7ccb8d8df48.png)

**Comment by DamnWidget** [comment]
What you mean that you verified it by checking `sys.prefix`? If you checked `sys.prefix` in Sublime Text 3 console you should get an empty string as the ST3 embedded interpreter is built into the C++ ST3 executable itself.

Anaconda is not able to expand the variable `$project_path` because the `extract_variables` window method was added to Sublime Text 3 API in build 3068 last Feb the 5th and it's still in the in-development branch that means that not anyone can access to this build.

Anaconda is not gonna be able to expand this variable until build 3068 becomes released to the general public. Until then, you should use absolute paths to your Python interpreter.

**Comment by jilves** [comment]
Okay, thanks.
