### ISSUE TITLE
Lack of new lines in tooltips

### ISSUE THREAD

**Issue by eujing** [DamnWidget/anaconda#280]
I noticed there was a lack of new lines from docstrings in the tooltips as '\n' is being used instead of \<br /\>
I have found by changing the relevant lines in listeners/signatures.py and commands/doc.py, the tooltips did seem to render new lines. Should I submit a pull request?

**Comment by DamnWidget** [comment]
Hi @eujing 
Thank you so much but I already have it solved (is not released yet because there are more things to fix and I want to improve the thing a bit). It was easier to fix it in `anaconda_lib/tooltips.py` by the way.

Of course I encourage you to contribute with anaconda in the future with more fixes and improvements.

Regards and thank you again.

**Comment by eujing** [comment]
No problem, thanks for the great plugin! The implementation of tooltips have really helped alot with development :)
