### ISSUE TITLE
Extremely slow after os x update

### ISSUE THREAD

**Issue by entron** [DamnWidget/anaconda#311]
I updated to the newest OS X yesterday (10.10.3), sublime text 3 is extremely slow. I removed anaconda, and the speed is fast again. Now I have to use sublime text without anaconda:(

**Comment by DamnWidget** [comment]
Hi.
If you only one change has been update OS X, it's obvious that something in the update has affected the plugin. With no more information I will just guess that your /etc/hosts file is corrupted and your OS X is not able to resolve the 'localhost' domain.

Give it a try.

**Comment by entron** [comment]
Thanks for the quick response! I checked the /etc/hosts file, and it looks fine. I also reboot the machine and the problem is still there.

**Comment by ghostwan** [comment]
I have the same problem with yosemite 10.10.2

**Comment by amikiri** [comment]
I've got this issue too with OS X Yosemite. With anaconda enabled, Sublime is super slow, like typing on one of the old terminals using a 300 baud modem. Type, type, type then watch the characters slowly appear on the screen. Disable anaconda and everything works great but no autocomplete etc.

**Comment by mdzahidh** [comment]
Sam issue, has anyone figured it out yet ?

**Comment by entron** [comment]
Has any body figured out a solution?

**Comment by DamnWidget** [comment]
I have no problems to run anaconda with the latest version of Yosemite, if
anaconda was working fine before you updated OS X, probably the problem is
in the update itself (/etc/hosts file being corrupted and anaconda not
being able to connect to "localhost"?). Also make sure that your configured
python interpreter is right and available. Check the console logs in seek
of clues is not much what we can do to support you guys about an update in
your operating system.

On 31 August 2015 at 11:09, Cheng Guo <notifications@github.com> wrote:

> Has any body figured out a solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/311#issuecomment-136322518>
> .
>



-- 
Join the Free Software Foundation and become Free as in Freedom

**Comment by entron** [comment]
Thanks for replying. I just give another try by remove and reinstalling package control in sublime text 3 and it works!

**Comment by DamnWidget** [comment]
Glad to see that you managed to solve the problem :)

On 31 August 2015 at 11:55, Cheng Guo <notifications@github.com> wrote:

> Thanks for replying. I just give another try by remove and reinstalling
> package control in sublime text 3 and it works!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/311#issuecomment-136334181>
> .
>



-- 
Join the Free Software Foundation and become Free as in Freedom
