### ISSUE TITLE
Autocompletion for tkinter module unavailable

### ISSUE THREAD

**Issue by cryzed** [DamnWidget/anaconda#315]
I am running Windows 7 using Sublime Text 3, Build 3085 and Python 3.4.3 as the configured interpreter. I distinctly remember autocompletion working for the tkinter module at some point (maybe when using Python 2), but it seems to have stopped on my configuration for some reason. The configured Python interpreter is on the standard path (not a virtualenv) and autocompletion for other modules works flawlessly.

**Comment by cryzed** [comment]
I just copied the tkinter package from C:\Python34\Lib directly next to the script that I am trying to import it from, even then the autocompletion doesn't work and I can't jump to the definition either with the message: "[Unable to find tkinter](http://i.imgur.com/uFHIa91.png)".

**Comment by DamnWidget** [comment]
Hi @cryzed 
Probably a bug in the Jedi version that we are using now. I just tested in a Python3 interpreter and I didn't got any completion neither (you can easily test it with this piece of code into a Python interpreter inside the `anaconda_lib` directory `print(Script('import Tkinter as Tk; Tk.').completions())`).

I think you should file a bug report about this in the [Jedi library Github project site](https://github.com/davidhalter/jedi/issues) try to find an already open issue because is quite possible that this is a known issue already as Tkinter is very popular.

**Comment by cryzed** [comment]
There was no issue that mentioned this bug. You can see the created issue above.

**Comment by DamnWidget** [comment]
Closing this issue as it was already addressed by @davidhalter in Jedi
