### ISSUE TITLE
anaconda autocompletion within markdown fenced code blocks

### ISSUE THREAD

**Issue by shaunpatel** [DamnWidget/anaconda#321]
Is is possible to use anaconda's autocompletion features within fenced python code blocks in a markdown file? Perhaps through a scope selector?

**Comment by DamnWidget** [comment]
Anaconda disables itself from work in source code that is not Python/Code using the functions defined in [here](https://github.com/DamnWidget/anaconda/blob/master/anaconda_lib/helpers.py#L36) and [here](https://github.com/DamnWidget/anaconda/blob/master/anaconda_lib/helpers.py#L61) I think is perfectly possible.

Said that, I am not working with Python since eight months ago so I am not using anaconda myself too much lately. That means that Pull Requests are welcome :)
