### ISSUE TITLE
Rename object under cursor has errors in it's string editing

### ISSUE THREAD

**Issue by LangdalP** [DamnWidget/anaconda#394]
I'm not sure what causes it, but for some renames, the function doesn't properly edit the source code.

One way I could reproduce it was when renaming a function called update_person_with_api_data. When I renamed it to update_person_with_api_data2, and then back to update_person_with_api_data, it removed the paranthesis for the start of the parameter list.

Here is a gif of it happening: http://i.imgur.com/WzmxJ2B.gifv

**Comment by DamnWidget** [comment]
I will take a look as soon as I have some time to do it

**Comment by DamnWidget** [comment]
That is because you didn't saved the file after the first rename and Jedi makes it changes in the saved file in the file system, if you save the file you get the right behavior. The only solution is to force ST3 to save the new buffer after the rename, not sure if I want to do that, probably is fine but I think is a bit intrusive.

**Comment by LangdalP** [comment]
Ok, I guess that's fine, I can live with it now that I know that I have to save between renames.

Doesn't ST3 support working on an in-memory text buffer instead of having to go through the file?

**Comment by DamnWidget** [comment]
Yes, ST3 do it but Jedi, the library that we use to support big part of our functionality doesn't

**Comment by DamnWidget** [comment]
Can we close this?

**Comment by LangdalP** [comment]
If you're asking me then yes.
