### ISSUE TITLE
Anaconda can't find import definition

### ISSUE THREAD

**Issue by jseaidou** [DamnWidget/anaconda#440]
```
import sys


def main():
    print("hello")
    sys.exit(status=-1)


if __name__ == "__main__":
    main()
```
Consider that snippet. If I try and go to the definition of sys.exit I get: Unable to find exit
However I can see the docstring for exit as I am typing it out.

**Comment by DamnWidget** [comment]
That is because autoimport and completion/documentation are two different subsystems, let's say that autoimport is a complicated feature to implement and my implementation is not the best in the world, there are plans to improve it but I didn't had enough time to do it yet.

**Comment by jseaidou** [comment]
Sorry I might have not explained properly, is going to the source definition ( implementation) part of importing? If I can go to main on line 4 from line 10, how is that different from going to definition of exit from line 6

**Comment by DamnWidget** [comment]
That is because sus.exit is a built-in python función written in C language so it's compiled into the Puthon binary (or one shared library) as machine code so anaconda has no way to jump to the definition of that code.

You can see the `sys.exit` implementation here https://github.com/python/cpython/blob/master/Python/sysmodule.c#L261

**Comment by jseaidou** [comment]
Ahh my mistake I thought it had a Python implementation. Thanks!
