### ISSUE TITLE
Case sensitivity prevents using  gutter mark themes

### ISSUE THREAD

**Issue by mbo42** [DamnWidget/anaconda#443]
The icons in Packages/Anaconda/anaconda_lib/linting/gutter_mark_themes/ are named in all lower case, but the code refers to them in proper case. 
This results in '**Unable to decode**' errors and a weird orange icon.
Possibly only affects Linux users.

Workaround is to rename the Icons to have a capitalised first letter.

**Comment by DamnWidget** [comment]
Make sure that in your configuration the name of the theme is lowercase, solution in any case could be to convert anything that is contained in the `anaconda_gutter_theme` to lowercase instead of rename the themes to capitalize them.

Anyway, your problem is that you named it capitalized in your config file.
