### ISSUE TITLE
Linter doesn't recognize python3-compatible `super().__init__()`

### ISSUE THREAD

**Issue by ex-nerd** [DamnWidget/anaconda#444]
The following import from future should work:

```python
from builtins import super

class A(object):
    def init(self):
        pass

class B(A):
    def init(self):
        super().__init__()
```

But the linter complains about the last line, expecting super() to behave like old-style python 2 with a parameter.

**Comment by DamnWidget** [comment]
Can't replicate, make sure your configured interpreter is set to a valid python3 interpreter.

![444_not_replicable](https://cloud.githubusercontent.com/assets/329766/13424073/6b841d40-df96-11e5-972b-1d61d12296c6.png)

**Comment by ex-nerd** [comment]
I'm not using a python3 interpreter. That's the point of using `from builtins import super`  It gives the python3 behavior in python 2.

**Comment by DamnWidget** [comment]
Oh, sorry, I didn't noticed about the future import (crazy days at work). Unfortunately this is still not replicable.

![issue_444](https://cloud.githubusercontent.com/assets/329766/13459222/2d77900c-e06a-11e5-9670-1940ee795eb7.png)

**Comment by ex-nerd** [comment]
I can't seem to get anaconda to import into my ST3 console to check that value but I'm not doing any overrides, just the basic OSX default python.  Something is definitely different about  my setup, since I'm getting a lot more warnings than you are, too:

![screenshot 2016-03-02 14 14 55](https://cloud.githubusercontent.com/assets/154074/13477440/39a8eda0-e081-11e5-9bcf-11fa30f366b5.png)

**Comment by DamnWidget** [comment]
That is because you installed it from PackageControl, in that case the package name is `Anaconda` and not `anaconda`. About the issue itself:

1. Which linter are you using?
2. Do you have a local version of PyFlakes or pep8 installed in your environment? If you have, please, consider to remove it, anaconda pack's its own versions (you can also create a virtual environment that will not use your system packages and use it as your anaconda isolated interpreter, then you can install whatever library that you need completion support for in that environment)

**Comment by DamnWidget** [comment]
Any feedback here?

**Comment by ex-nerd** [comment]
Closing.  I upgraded/changed something and now everything's working fine.
