### ISSUE TITLE
Completion list flickering

### ISSUE THREAD

**Issue by skaughtx0r** [DamnWidget/anaconda#478]
I'm having an issue on windows when the completion list is displayed, it starts flickering. I was able to fix it by commenting out the following line.

https://github.com/DamnWidget/anaconda/blob/e20c02ef5ef4590932b285ad27af20c19c635d28/listeners/completion.py#L83

Looking at the console, `on_query_completions` is called very frequently when the completion list is being displayed and it seems like every call is making the list hide/show causing it to flicker.

**Comment by DamnWidget** [comment]
I already commented in the original "flickering" issue, here is the link to the comment: https://github.com/DamnWidget/anaconda/issues/244#issuecomment-216586614

You will not get any flickering at all in any platform when you use anaconda, it is probably caused by any other package interfering with ST3 completion mechanism, please, disable any other Python auto-completer package while using anaconda.

**Comment by skaughtx0r** [comment]
Thanks for the response, I couldn't find anything when searching the issue online (other than the previous issue in this repo).

It was definitely a conflict with some other package. I went through and pruned a bunch and it started working. normally.

**Comment by DamnWidget** [comment]
Can I know which one was?

**Comment by skaughtx0r** [comment]
Ha yeah, I feel kind of stupid, turns out I had installed JEDI at some point in the past and forgot about it.
