### ISSUE TITLE
Anaconda does not show function docs afters using decorator

### ISSUE THREAD

**Issue by danceasarxx** [DamnWidget/anaconda#499]
Anaconda refuses to show the documentation of any function that has been decorated even after using 
`functools.wraps`. Rather than that it shows the name of the decorator. I don't really think I need to show an example but just in case

```python
def do_good():
    '''
    do_good_docs.
    '''
    pass

assert do_good.__docs__ == 'do_good_docs'

from functools import wraps
decorate(fn):
    @wraps(fn)
    def dec():
        fn()
    return dec

def do_good_dec():
    '''
    do_good_docs.
    '''
    pass

assert do_good_dec.__docs__ == 'do_good_docs'

```

**Comment by danceasarxx** [comment]
This is really bad PR

**Comment by DamnWidget** [comment]
What you mean?

**Comment by danceasarxx** [comment]
Long after I have closed the ticket...I created this issue over one month ago...changed to emacs, came back to sublime and it still wasn't solved. And by the way....what do you mean by "What do you mean"

**Comment by DamnWidget** [comment]
You said 'this is really a bad PR' normally here in GitHub PR is used to refer to Pull Request, there is no pull request involving this issue so that is why I asked what did you meant.

Btw, the issue is with Jedi the completion library, there is nothing that we could do except wait until they fix the issue in their side.

**Comment by danceasarxx** [comment]
No problem, don't need the solution anymore...thanks regardless
