### ISSUE TITLE
Anaconda doesn't work

### ISSUE THREAD

**Issue by linjunshi** [DamnWidget/anaconda#531]
It report numerous syntax error when it's actually a valid syntax, I've tried to change the default interpreter to python3 but it does't work, and intellisense doesn't work either.

**Comment by DamnWidget** [comment]
If it reports syntax errors is because there are syntax errors, make sure you are not mixing spaces and tabs, go line by line and read the description of the error in the status bar.

**Comment by linjunshi** [comment]
![image](https://cloud.githubusercontent.com/assets/14053321/18259707/5380b55e-742a-11e6-8197-201695606258.png)

I didn't use tabs, its syntax is valid and I can run it, but anaconda just shows me 'line too long'
![image](https://cloud.githubusercontent.com/assets/14053321/18259749/d03a58c0-742a-11e6-8b91-a22cd504e1a4.png)

and missing whitespace after ','
![image](https://cloud.githubusercontent.com/assets/14053321/18259757/e618d59a-742a-11e6-8797-672e51643672.png)
the missing whitespace after ',' I don't think it's necessary because it's valid, how can I  change the setting?
And another thing is the intellisnese doesn't work, thank you so much, really appreciate your help.

**Comment by DamnWidget** [comment]
Well, that is what we know as a [PEP8](https://www.python.org/dev/peps/pep-0008/) syntax violation warning, PEP8 warnings are not syntactical errors but warnings about you not following the Python conventions for writing code that the whole community put effort into.

PEP8 is important because it makes possible for any Python programmer in the world (that follows and knows about the PEP8) to quickly understand and get familiar with anyone else Python code (always that both of them are following the PEP8).

If you really want to suppress PEP8 linting you can do it just setting `pep8` as `false` in the configuration file but *i really discourage* such action, is much better for you to get used to the Python community conventions and follow them, if you do, you will grow as programmer, the other way around is not true.

By the way, you may want to tune your Theme settings to make anaconda lint in different colors by severity the lines that contains any kind of problem. If you do, syntax errors will be linted as red while warnings and small violations will be linted in yellow and white respectively.

If you want to customize your theme just [follow the instructions](https://github.com/DamnWidget/anaconda/wiki/Linting-theme-customization) from the wiki.

**Comment by linjunshi** [comment]
@DamnWidget 
I'm so sorry, I apologise for saying that the warnings are unnecessary because I didn't know about the pep8 and some conventions in python community.
I've changed the interpreter to python3 but it's still unable to get those functions from pandas and numpy.

**Comment by DamnWidget** [comment]
Don't need to apologise, pandas and numpy are known to have some problems with Jedi the underlying library that we use to get autocompletion probably is related to that.
