### ISSUE TITLE
Lint description/message not always shown

### ISSUE THREAD

**Issue by AllanLRH** [DamnWidget/anaconda#533]
Sometimes Anaconda will only show a lint error code, and leave out the description. Would be handy to always see the linter message.
See this example screenshot:
![screen shot 2016-09-05 at 16 11 58](https://cloud.githubusercontent.com/assets/2641327/18274433/abc23fae-7442-11e6-8f3e-4ac731d8dbbd.png)

**Comment by DamnWidget** [comment]
Can you run "Show linter errors"? It looks like another plugin is eating the error description from the status bar.

**Comment by AllanLRH** [comment]
It just says _14_.
When I run pep8 in the file in terminal, the line in question returns `nbiprintSupportFunctions.py:12:16: E127 continuation line over-indented for visual indent`.

In this screenshot I've disable he _Git_ plugin in order to make some more room in the status bar.

![screen shot 2016-09-06 at 22 40 31](https://cloud.githubusercontent.com/assets/2641327/18290293/4582a71a-7483-11e6-8689-e9eaa5fd6152.png)

**Comment by DamnWidget** [comment]
I could replicate this, seems like there is line truncation in other PEP8 messages as well. Btw yeah, I meant that anaconda command, is hard to remember everything in a huge project like this one.

**Comment by DamnWidget** [comment]
Discover what was going on with this one has been a pain. The culprit was `autopep8` that we use to automatically format the buffer.

Seems like `autopep8` overrides some `pep8` check functions by it's own, there was a disconformity in how our version of `autopep8` decided to report back errors to `pep8`. I just upgraded both `pep8` and `autopep8` libraries to match their formats.

Pending for release.
