### ISSUE TITLE
False positives in the linter with error 305 (E305)

### ISSUE THREAD

**Issue by vmachiel** [DamnWidget/anaconda#561]
So 305 regards the two expected blank lines after a function or class definition. Fair enough, but it also triggers after assignment of global variables and constants. See image below: all are E305. 

http://i.imgur.com/C1FPliD.jpg

**Comment by DamnWidget** [comment]
Hi, all I can see is an screenshot of something being linted in that lines
but there is no any error context, can you add a screen of the list of the
errors?

**Comment by vmachiel** [comment]
Sorry! All the errors are like this: 
http://imgur.com/77AMQ96.jpg

**Comment by vmachiel** [comment]
And they are not class of function definitions.

**Comment by DamnWidget** [comment]
That is coming directly from the `pycodestyle` (formerly pep8.py) library and I guess is because the name of those variables contains the word `class`. This was reported by other user in #542 that even provided a solution in #543 but that is a problem in PyCodeStyle that they must fix themselves we can't just modify a third party library as it will be painful to maintain.

**Comment by DamnWidget** [comment]
In fact the same user made a PR in pycodestyle directly https://github.com/PyCQA/pycodestyle/pull/576#pullrequestreview-1514601 but it is waiting merge because of tests (that seems to be now provided), so is a matter of wait.

**Comment by vmachiel** [comment]
I see! Thanks so much. I'll close the issue.
