### ISSUE TITLE
The preferred place to break around a binary operator is before the operator

### ISSUE THREAD

**Issue by NicolasRaus** [DamnWidget/anaconda#586]
## Expected Behaviour
https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

> For decades the recommended style was to break after binary operators. But this can hurt readability in two ways: the operators tend to get scattered across different columns on the screen, and each operator is moved away from its operand and onto the previous line. Here, the eye has to do extra work to tell which items are added and which are subtracted:
> 
> ```
> # No: operators sit far away from their operands
> income = (gross_wages +
>           taxable_interest +
>           (dividends - qualified_dividends) -
>           ira_deduction -
>           student_loan_interest)
> ```
> To solve this readability problem, mathematicians and their publishers follow the opposite convention. Donald Knuth explains the traditional rule in his Computers and Typesetting series: "Although formulas within a paragraph always break after binary operations and relations, displayed formulas always break before binary operations" [3] .
> 
> Following the tradition from mathematics usually results in more readable code:
> 
> ```
> # Yes: easy to match operators with operands
> income = (gross_wages
>           + taxable_interest
>           + (dividends - qualified_dividends)
>           - ira_deduction
>           - student_loan_interest)
> ```
> In Python code, it is permissible to break before or after a binary operator, as long as the convention is consistent locally. For new code Knuth's style is suggested.

## Actual Behaviour
When breaking before the operator, I get 

> PEP 8 (W503): line break before binary operator.

As it says in the PEP 8 documentarion, it's permissible to break before or after. So W503 should be removed

**Comment by DamnWidget** [comment]
You probably want to report this into https://github.com/pycqa/pycodestyle project, we use them to lint PEP8.

In the meanwhile you can add `W503` to the `pep8_ignore` list in your settings.

**Comment by Liorinco** [comment]
Hi!
The issue seems to be managed from pycodestyle: https://github.com/PyCQA/pycodestyle/blob/master/pycodestyle.py#L84
When we call the command line, the issue is no more raised, but it is always by anaconda.

Will you manage this update or developers will have to continue to confirm this is not a real issue and add `W503` in the `pep8_ignore` setting?

**Comment by dragos240** [comment]
This is still a problem in the current version of Anaconda (on packagecontrol.io). I need to add `W503` to `pep8_ignore` since `W503` AND `W504` are [both enabled by default](https://gitlab.com/pycqa/flake8/-/issues/466), leading to making it always complaining about one of them without changing the user config. I suggest adding this to the default `pep8_ignore` config so that this problem is not something the user needs to fix.

**Comment by thegnarwhals** [comment]
Thank you @DamnWidget ! Is there a release scheduled that this could be incorporated into? Any way I can help on that front?

**Comment by DamnWidget** [comment]
> Thank you @DamnWidget ! Is there a release scheduled that this could be incorporated into? Any way I can help on that front?

I forgot to release it, will do it shortly

**Comment by thegnarwhals** [comment]
Thanks so much @DamnWidget :clap:
