### ISSUE TITLE
Enum module backport incompatible with higher versions of python

### ISSUE THREAD

**Issue by Elliot2560** [DamnWidget/anaconda#596]
The `enum` module included in the `anaconda_lib` directory is from an earlier version of python 3.4, and is out of date when used with later versions of python. This causes issue because the `socket` module (in 3.5.2) calls `_convert` as a class method from `IntEnum`, which was not defined in earlier versions. This causes the import of `socket` in `jsonserver.py` to fail, crashes the server, and then triggers an infinite sequence of attempts to start jsonserver.

## Steps to Reproduce
This error happens whenever the worker attempts to start a jsonserver. 

The symptoms are similar to some previous issues (such as [#558](https://github.com/DamnWidget/anaconda/issues/558), [#527](https://github.com/DamnWidget/anaconda/issues/527), [#514](https://github.com/DamnWidget/anaconda/issues/514), and [#575](https://github.com/DamnWidget/anaconda/issues/575)), but the cause seems to be different, as those issues don't seem to have been produced under python 3.5+.

It is not possible, however, to work around this by copying/symlinking the new version of `enum` to the `anaconda_lib` directory, because at startup the plugins are imported in the embedded python 3.3 environment of sublime text, so the 3.5 version of `enum` will trigger an `ImportError`. 

## ST3, Anaconda and OS versions
I'm running ST3 build 3126, on 64bit Arch Linux, with Anaconda up to date, at 2.1.10.

**Comment by DamnWidget** [comment]
Good catch.

If I understand this, the Python interpreter running the  JsonServer `socket` module is using the `enum` module inside `anconda_lib` instead of the one in it's own library path?

I use Python 3.5 and never had this problem and I am not able to reproduce it myself, anyway, I will update the `enum` module in the `anaconda_lib` so you can test it yourself.

And good catch again.

**Comment by Elliot2560** [comment]
Yes. That is exactly what happened. In fact, if I start sublime text with the `enum.py` file originally included in the package, and then just delete it, then the JsonServer can start normally, since the python interpreter defaults to the native `enum` module.

**Comment by Elliot2560** [comment]
Oh... and I just discovered why I see this issue but you can't reproduce it. I had my `$PYTHONPATH` set to `/usr/lib/python3.5/site-packages/:/usr/lib/python2.7/site-packages/`, which probably messed with how `sys.path` was set pretty hard. I don't quite recall why I did that, but that did not seem like a smart move...

**Comment by DamnWidget** [comment]
Unfortunately the fix breaks anaconda_go so it will take a while

**Comment by cbueltem** [comment]
I have installed Sublime Text 3 and Anaconda a few days ago - and I'm facing exactly the same problem. How can I get rid of this? Working in Win 10 with Python 3.5, SublimeText Version 3, build 3126, Anaconda version 2.1.15. 
There is no enum.py file in the anaconda_lib. However the described symptoms are shown. Once a .py file is opened Sublime Text is repeatedly throwing error messages unless it is closed.

**Comment by DamnWidget** [comment]
The file is called `aenum.py` not `enum.py`, by the way, why you have a subdirectory of the same directory as your `PYHONTPATH` you should have only one of them. 

If you could paste the errors that you get I would probably offer much better help than just guessing

**Comment by cbueltem** [comment]
The issue was exactly identical to the one described in the first post by Elliot2560. First I got this:

![grafik](https://cloud.githubusercontent.com/assets/26336390/23822753/8eeb4ad0-0653-11e7-81cd-43fa4d6348a7.png)

Thenafter an infinite loop of dialog boxes stating that Python has crashed. 

**However** - I checked my PYTHONPATH. The second directory exists but it does not contain any modules so I removed it. Surprisingly the infinite loop is gone. Now SublimeText/Anaconda works after ignoring the first error message (see screenshot). So I will set the swallow_startup_errors and start happily using anaconda.
