### ISSUE TITLE
"Your python interpreter is not set or is invalid" error on loading python files

### ISSUE THREAD

**Issue by optimuspaul** [DamnWidget/anaconda#607]
## Expected Behaviour

Open a python file and not be bothered with errors that make no sense.

## Actual Behaviour

First time opening a `.py` file for a window(project?) produces a 

## Steps to Reproduce

- Install ST3 on OS X Sierra
- install Anaconda plugin (maybe, I didn't, it was just there or was installed by some other plugin)
- open a folder containing some `.py` files
- open a `.py` file
- be annoyed (this is important)

## ST3, Anaconda and OS versions

ST3 build 3126
Anaconda 1.4.26
OS 10.12.2

## ST3 Console Logs

nothing in the console log

## Anaconda's JsonServer Logs

No logs exist at the locations described

## Notes

I tried setting the `python_interpreter` setting to no avail. I also am using pyenv with virtual environments, not sure if that is causing some side effects.  Oh and did I say I get the error message twice every time but only on the first file opened? No, yeah well that happens.

**Comment by DamnWidget** [comment]
You are using an almost one year old anaconda version, install a recent version.
This report is pretty annoying by the way, there is much better ways to ask for support than what you did.

**Comment by optimuspaul** [comment]
upgraded to most recent, still see the error. What are these other support options you speak of?

This seems like an issue to me, maybe the issue is documentation, maybe it's bad code, maybe it's user error. But if you don't want this to be a valid support channel then make that super clear, because it isn't. I'm sorry you are annoyed by it.

**Comment by DamnWidget** [comment]
The documentation is at your disposal in the following link http://damnwidget.github.io/anaconda/anaconda_settings/ 

I am complaining about the way that you wrote your ticket, the irony and the aggressive tone like "errors that make no sense".

There are thousand of users that use this plugin every day, if you get an error is because probably there is a problem with your configuration/environment,  the errors makes perfect sense and they are triggered for good reasons.

Do not forget that we support and maintain this software freely, being nice is also free.

**Comment by optimuspaul** [comment]
I wrote the ticket using the template provided. I was just trying to be funny. Sorry that you didn't find the humor in it. I thought I was being nice. To be fair, the error didn't make sense, still doesn't even after I read the docs. I have a valid python interpreter on my PATH, why wasn't it found? Also why twice?  Maybe add that exact error message to the docs so that when someone does a search for that they end up there. I'm surprised that the default didn't work, python is on my path, ¯\\_(ツ)_/¯ 

Sorry to be a bother, I meant no harm. Also keep in mind being nice is free, even when you feel others are not. 😄

**Comment by optimuspaul** [comment]
Oh I just realized, it's my avatar, it's kind of an angry face, maybe that set the tone.

**Comment by DamnWidget** [comment]
Well is hard to get the tone of things in written media, you know.

Can you paste your settings here? Make sure that you understood about the different configuration levels, some times people is overriding the settings in a more specialized level and they get unexpected results.

**Comment by optimuspaul** [comment]
I updated the Global settings, set the `python_interpreter` to the absolute path of mine, `/usr/local/opt/pyenv/shims/python`. That didn't seem to make a difference. I did then also set the `auto_python_builder_enabled` to `false` which maybe did the trick. I don't have any User settings at all and I don't use Projects yet for anything either. So that should be the only settings consulted.. unless the lack of settings at those stages unsets the global setting, but that doesn't seem plausible, right?

Yes, tone is hard to read, which is why I always (try to) assume the best possible intent. Apply that to reading online things and kids for improved happiness. It can be hard when there is an avatar with teeth bared staring you down.

**Comment by DamnWidget** [comment]
If I understood, the problem is gone after you did set `auto_python_builder_enabled` to `false`? That is interesting.

Anaconda tries to add a custom Python Builder using your configured `python_interpreter` when it first initializes its `workers`. It first checks that a project exists for the active window session and if it does, then it calls the necessary methods to update your project python builder settings passing your `python_interpreter` to them.

For some reason your Python interpreter was set as `None` and that is why you were getting the error message. You were getting it twice because anaconda tries to initialize it's workers subsystem asynchronously so your client tried to start another worker to make the Python Builder to work while the first worker was already initializing the system.

Which other plugins do you have installed alongside anaconda?

**Comment by optimuspaul** [comment]
I have:

- Pretty JSON
- Pretty YAML
- SublimeCodeIntel
- SublimeLinter
- Lua Dev
- Markdown Preview
- Python 3  <-- something tells me it's this one that is causing problems.

**Comment by DamnWidget** [comment]
We have a winner, `SublimeCodeIntel` is known for being a bad neighbour, you need to disable it for Python (if it allows you to do it at all) or just disable the whole thing while you use Anaconda, it is known to interfere with any other auto-completion plugin and they hardcode things like trigger autocompletion events when you write the colon symbol (that is completely useless and annoying in Python code cos you get an auto-completion popup just before hit enter after a conditional o function declaration or loop or whatever that ends in colon).

Python 3 works fine with anaconda.

**Comment by optimuspaul** [comment]
I've always hated that thing, but nothing worked as well on ST2.  Thanks!

**Comment by DamnWidget** [comment]
You are welcome, and sorry for the miss understanding 👍
