### ISSUE TITLE
I can't type damn left parenthesis after installing your package.

### ISSUE THREAD

**Issue by scythargon** [DamnWidget/anaconda#613]
Sublime 3, ubuntu 16.10

**Comment by scythargon** [comment]
reproduce:
open sublime, new file, set syntax python, try to type "(" character, nothing happens

```
DPI scale: 1
startup, version: 3114 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/argon/.config/sublime-text-3/Packages
state path: /home/argon/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/argon/.config/sublime-text-3/Installed Packages
ignored_packages: ["ElixirSublime", "Python Flake8 Lint", "Vintage"]
pre session restore time: 0.080868
startup time: 0.159467
first paint time: 0.162283
first paint time: 0.169209
Unable to fetch update url contents
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Django Tags.django_template_tags
reloading plugin Javascript Beautify.jsbeautify
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SqlBeautifier.sqlbeautifier
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin Jedi - Python autocompletion.__init__
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2017-02-09 17:44:58, next run at 2017-02-09 18:44:58 or after

```

**Comment by DamnWidget** [comment]
Uninstall or disable damn Jedi Autocompletion ;)

On Feb 9, 2017 13:36, "scythargon" <notifications@github.com> wrote:

reproduce:
open sublime, new file, set syntax python, try to type "(" character,
nothing happens

DPI scale: 1
startup, version: 3114 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/argon/.config/sublime-text-3/Packages
state path: /home/argon/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/argon/.config/sublime-text-3/Installed Packages
ignored_packages: ["ElixirSublime", "Python Flake8 Lint", "Vintage"]
pre session restore time: 0.080868
startup time: 0.159467
first paint time: 0.162283
first paint time: 0.169209
Unable to fetch update url contents
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Django Tags.django_template_tags
reloading plugin Javascript Beautify.jsbeautify
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SqlBeautifier.sqlbeautifier
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin Jedi - Python autocompletion.__init__
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2017-02-09
17:44:58, next run at 2017-02-09 18:44:58 or after


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DamnWidget/anaconda/issues/613#issuecomment-278642283>,
or mute the thread

**Comment by lvalladares** [comment]
Having the same problem, jedi already uninstalled

**Comment by nightlifelover** [comment]
Please fix this, also have it on Ubuntu and had to uninstall it :( On my Mac however it works w/o problems.

**Comment by nightlifelover** [comment]
Thx for the quick answer!

**Comment by codelinx** [comment]
Quick fix that helped me on my Mac: 

**_Sublime Text > Preferences > Package Settings > Jedi > Keymap - Default ~>_**
_Changed this line #12:_
`	{"command": "sublime_jedi_params_autocomplete", "keys": ["("],`
to 
`	{"command": "sublime_jedi_params_autocomplete", "keys": ["super+ctrl+j"],`

**Comment by skypanther** [comment]
Changing Keymap - User didn't work. I had to change Keymap - Default per the above comment. My left parens are back!

**Comment by shaharkadmiel** [comment]
@codelinx solution works for me as well. Why the hell would this even be an issue?

**Comment by soulslicer** [comment]
This is hilarious

**Comment by zhFuECL** [comment]
Why use this binding "(" ? It's awful!

**Comment by DamnWidget** [comment]
Anaconda does not binds the parentheses, please comments about other projects to their respective repos

**Comment by DamnWidget** [comment]
Anaconda doesn't add any key binding for the left parenthesis as I already said in the previous comment.

**Comment by oferchen** [comment]
This is such a waste of time can't the default be modified to something less useful?

**Comment by DamnWidget** [comment]
You should probably try to open a ticket in the project that is actually setting the binding, Anaconda does not set any binding in your left parenthesis, you can complain as much as you want in here but there is nothing that we can do about because that binding is being set by other plugin.

**Comment by Penagwin** [comment]
I think they did that so they can hook into the event to show you some of the suggestions. But since anaconda is doing it instead nothing happens.

My initial reaction anyway.

**Comment by digitalformula** [comment]
FWIW, even today in May 2019 it's still an issue (yes, with Jedi not playing nicely with Anaconda, but whatever).  The fix by @codelinx is still the way forward.

**Comment by frankjing** [comment]
2019-08-02 still the same issue, still the same fix by @codelinx works.

**Comment by hseritt** [comment]
You've got to be kidding me that this issue still exists. Who in the hell uses a left parenthesis as a key binding???

**Comment by stfuanu** [comment]
> Quick fix that helped me on my Mac:
> 
> **_Sublime Text > Preferences > Package Settings > Jedi > Keymap - Default ~>_**
> _Changed this line #12:_
> ` {"command": "sublime_jedi_params_autocomplete", "keys": ["("],`
> to
> ` {"command": "sublime_jedi_params_autocomplete", "keys": ["super+ctrl+j"],`

4 years and still not fixed , thanks @codelinx for solution 👍
