### ISSUE TITLE
can't uninstall anaconda plugin from sublime 3

### ISSUE THREAD

**Issue by daryanypl** [DamnWidget/anaconda#641]
## Expected Behaviour
For the silly code linter square rectangles to stop appearing on sublime restart, without me having to disable anaconda linting on every restart.

## Actual Behaviour
Rectangles appear, anaconda package preferences appear, anaconda is not being uninstalled.

## Steps to Reproduce
rm -R ./Users/[me]/Library/Application\ Support/Anaconda 
rm ./Users/[me]/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Anaconda.sublime-settings
rm -R ./Users/[me]/Library/Application\ Support/Sublime\ Text\ 3/Packages/Anaconda

## ST3, Anaconda and OS versions
ST3, build 3126

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
Can you explain me how you think anaconda installs all by himself in your computer after you remove it? If you are using Package Control (that you are because you directory name is `Anaconda` and git installations are `anaconda` in lowers) just use the Package Control uninstall command because is more than probably that Package Control is reinstalling the plugin.

If you think the rectangles are "so silly" you have several options to disable the whole linter, or even just disable the rectangles or modify the look and feel of the linter reports in any imaginable way as absolute all the anaconda features are configurable and possible to turn off.

A quick look at the config file will suffice to know how to properly configure it to adapt it's behavior to your needs but you can also find all the related information in the extensive AnacondaST3 users documentation:
* [Disabling the linter](http://damnwidget.github.io/anaconda/IDE/#disabling-the-linter)
* [Linter Look & Feel](http://damnwidget.github.io/anaconda/IDE/#look-feel)

If you don't know how to use Package Control it's [official documentation](https://packagecontrol.io/docs/usage) site will be a good starting point
