### ISSUE TITLE
Two problems about anaconda in Sublime Text3

### ISSUE THREAD

**Issue by coderchaser** [DamnWidget/anaconda#664]
## Expected Behaviour
Two behaviours that I want anaconda do:
1:When I `import` more than one modules separated by `,`(comma),it can auto-complete every module's name
2:I set the `python_interpreter` as `python3.4`.When I type `pri`,I want it to auto-complete this to `print()`
## Actual Behaviour
1:The anaconda can only auto-complete the first and fails during the rest modules.Such as `import sys,math`,it can only auto-complete `sys`,fail `math`.
2:It auto-complete `pri` to `print`,like print in Python2.7
## ST3, Anaconda and OS versions
ST3 Build3126, V2.1.18, Ubuntu 12.04 LTS
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
Hi,
About 1, that is a limitation of Jedi, if anaconda does not offers completions is because Jedi doesn't return any (by the way, multiple module imports in the same line is a PEP8 violation)

About 2, did you tried to enable the parameters completion?. Set `complete_parameters` as `true` in teh configuration.

**Comment by coderchaser** [comment]
Hi,thank you.
I set `complete_parameters` as `true`,it still fails to auto-complete the brackets.

**Comment by DamnWidget** [comment]
Are you sure that you configured a Pyuthon3 interpreter?

**Comment by coderchaser** [comment]
The Default `python_interpreter` is `python`.Threr are both Python 2 and 3 in Ubuntu.So I set the `python_interpreter` as `python3.4`.Does this mean I set the interpreter as python3?

**Comment by DamnWidget** [comment]
Open your ST3 and edit a Python file in your project, open the ST3 console and write t he following:
```python3
from Anaconda.anaconda_lib.workers.market import Market; Market.get(Market, window.id()).interpreter
```
Paste here what you get back.

**Comment by coderchaser** [comment]
```
>>> from Anaconda.anaconda_lib.workers.market import Market; Market.get(Market, window.id()).interpreter
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'interpreter'
```

**Comment by DamnWidget** [comment]
That output is not possible if anaconda is really running, make sure the
plugin is running before run that command.

**Comment by coderchaser** [comment]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'interpreter'
>>> from Anaconda.anaconda_lib.workers.market import Market; Market.get(Market, window.id()).interpreter
python3 -B /home/bob/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p anaconda-2 2851
```

**Comment by DamnWidget** [comment]
That looks fine, if `python3` is a valid Python 3 interpreter you should be
getting the `print` function params. I double checked it and it works just
fine for me.

On May 27, 2017 16:12, "bobliao" <notifications@github.com> wrote:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'interpreter'
>>> from Anaconda.anaconda_lib.workers.market import Market; Market.get(Market, window.id
()).interpreter
python3 -B /home/bob/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py
-p anaconda-2 2851

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/DamnWidget/anaconda/issues/664#issuecomment-304458066>,
or mute the thread

**Comment by coderchaser** [comment]
OK,thank you.I will try to work it fine.
