### ISSUE TITLE
Anaconda does not work with 'localhost' as jsonserver bind address

### ISSUE THREAD

**Issue by landaire** [DamnWidget/anaconda#697]
I've been using Anaconda for a while on my machine without autocomplete working and today decided to finally figure out why it's not working. In the end, I ended up just trying to replace every instance of `localhost` in the source code with `127.0.0.1` and now autocomplete works fine. When I replaced only `jsonserver.py`'s address the server was able to start successfully but the client still failed. Once I changed *everything* it worked successfully.

Is there any reason why not to just use `127.0.0.1` as the bind address instead of depending on `localhost` resolution? I would be more than happy to make a PR with my changes but I wanted to first pose the question before I go down that route.

## Expected Behaviour

`jsonserver` should bind to `localhost`

## Actual Behaviour

On my machine, jsonserver fails to bind to `localhost`

## Steps to Reproduce

Launch a python project on my machine

## ST3, Anaconda and OS versions

- ST3 Build 3142
- Anaconda version v2.1.21 (latest as of today -- I uninstalled/reinstalled)

## ST3 Console Logs

(unavailable -- same as https://github.com/DamnWidget/anaconda/issues/296 though)

## Anaconda's JsonServer Logs

```
2017-09-07 19:30:24,741: ERROR   : Traceback (most recent call last):
  File "/Users/USER/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 340, in <module>
    server = JSONServer(('localhost', port))
  File "/Users/USER/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 156, in __init__
    self.bind(self.address)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 329, in bind
    return self.socket.bind(addr)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by DamnWidget** [comment]
Hi, I think you are making the wrong questions here. The question should be why your computer is not able to resolve localhost? 

`localhost` is being used universally everywhere because rely in a hardcoded IP is plainly wrong. 127.0.0.1 can work for you but doesn't necessarily have to work for other people, like for example people using IPv6 exclusively.

The `localhost` hostname is a IETF standard (RFC 6761) and a reliable way to resolve your loopback interface (that bypasses any network hardware and it's overheads). The solution to your problem must be to make your computer to resolve `localhost` as that is the right thing to do.

Try to put this in your `/etc/hosts` file:
```
127.0.0.1    localhost
::1          localhost
```

**Comment by landaire** [comment]
> Hi, I think you are making the wrong questions here. The question should be why your computer is not able to resolve localhost?

I actually did ask that question, but misread my hosts file. I had `::1` but no `127.0.0.1` entry..? I have no idea how that happened on my system. Adding in that entry fixed things though. That's super weird. You're right though, I posted the wrong solution to the right problem. Sorry about that.
