### ISSUE TITLE
Is the Anaconda package still being actively maintained? 

### ISSUE THREAD

**Issue by OdinTech3** [DamnWidget/anaconda#816]
I am wondering if this package has been abandoned by the developer?

**Comment by DamnWidget** [comment]
HI @OdinTech3 
I've been asking for maintainers for years now as I do not use SublimeText 3 since mid 2014 so my personal interest in the project has been going down along the years.

I just merge/discuss Pull Requests with fixes mainly, latest attempts to upgrade some of the components on the plugin resulted in performance problems and memory leaks (most specifically, latest two attempts of updating Jedi) so the only resolution was to roll back those.

I am not actively developing any new features or fixing non really breaking issues (I even quit Github some time ago, using Gitea and Gitlab mainly these days).

I understand this package is still widely used by Sublime Text 3 community and is sad that is almost archived, new maintainers are more than welcome I will be extremely open to give full permissions on the repository itself.

Regards.

**Comment by karolyi** [comment]
@DamnWidget just what I was asking for :) I'm happy to help you out here, as an active user of Sublime

What are you using for an editor nowadays? I still couldn't find anything that would beat Sublime.

**Comment by OdinTech3** [comment]
@DamnWidget  Thanks for responding. I was just curious to see what you hear about the state of the project.

Personally I kinda stopped using Anaconda myself and mainly use the LSP package together with palantir's python-language-server. However I do want to know how one can replicate the vagrant and docker integration you had in Anaconda which was awesome in LSP.

**Comment by karolyi** [comment]
@OdinTech3 honestly, I tried LSP about half a year ago but Anaconda still seemed way better in functionality. Has that changed ever since?

**Comment by OdinTech3** [comment]
@karolyi Yes it has very much, It's still has some  ways to go in terms of stability but nonetheless its pretty solid now

**Comment by DamnWidget** [comment]
@OdinTech3 all the related code is in this package https://github.com/DamnWidget/anaconda/tree/master/anaconda_lib/workers
